# Generated by Django 4.1 on 2024-04-01 11:20

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Бренд"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="media/brand-logo/",
                        verbose_name="Логотип",
                    ),
                ),
                ("url", models.SlugField(unique=True, verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Кольор"
                    ),
                ),
                ("url", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "col",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=8, samples=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Матеріал"
                    ),
                ),
                ("url", models.SlugField(unique=True, verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Назва Продукту"
                    ),
                ),
                ("url", models.SlugField(unique=True, verbose_name="URL")),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(to="store.color", verbose_name="Кольори"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.material",
                        verbose_name="Матерiал",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код Продукту"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="media/product_main_images/",
                        verbose_name="Головне Фото",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Кiлькiсть")),
                ("priceUAH", models.PositiveSmallIntegerField(verbose_name="Цiна")),
                (
                    "sale_priceUAH",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="Ціна зі знижкою"
                    ),
                ),
                (
                    "new_arrive",
                    models.BooleanField(default=True, verbose_name="Нещодавно доданий"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="store.color",
                        verbose_name="Кольор",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="store.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("CA", "Categories"), ("AC", "Accessories")],
                        max_length=2,
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=255, unique=True, verbose_name="Тип"),
                ),
                ("url", models.SlugField(unique=True, verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="ProductInventoryImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        upload_to="media/product_inventory_images/", verbose_name="Фото"
                    ),
                ),
                (
                    "product_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.productinventory",
                        verbose_name="Варіант Продукту",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductInventoryAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(max_length=255, verbose_name="Тип атрибуту"),
                ),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="Значення Атрибуту"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="store.productinventory",
                        verbose_name="Варіант Продукту",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.producttype",
                verbose_name="Тип Продукту",
            ),
        ),
    ]
