# Generated by Django 5.0.1 on 2024-02-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_id',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
