# Generated by Django 5.0.1 on 2024-02-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_brand_id_category_subcategory_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory_id',
            new_name='category_id',
        ),
    ]
