# Generated by Django 4.1 on 2024-03-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_sale_priceuah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_priceUAH',
            new_name='sale',
        ),
    ]
