# Generated by Django 4.1 on 2024-03-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='sale_priceUAH',
        ),
    ]
