# Generated by Django 4.1 on 2024-04-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_products",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="store.productinventory"
            ),
        ),
    ]
