# Generated by Django 4.1 on 2024-04-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
        ("users", "0002_user_favorite_products"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteProductTypes",
            new_name="FavoriteProductInventory",
        ),
        migrations.AlterModelOptions(
            name="favoriteproductinventory",
            options={"verbose_name": "Favorite Product"},
        ),
        migrations.AlterField(
            model_name="favoriteproductinventory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_products",
                to="store.productinventory",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("guest", "Guest")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="UserImage",
        ),
    ]
