# Generated by Django 4.1 on 2024-03-31 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_favoriteproducts_userimage_delete_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorite_products",
        ),
    ]
