# Generated by Django 4.1 on 2024-04-10 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_active_alter_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoriteproductinventory",
            name="added_at",
        ),
    ]
