# Generated by Django 4.1 on 2024-04-10 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
